SELECT * FROM PIZZA_SALES

/* A- KPI'S REQUIREMENT*/

/*A-1*/ --Total Revenue
SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES

/*A-2*/ --Average order value 
SELECT (SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID)) AS AVG_ORDER_VALUE FROM PIZZA_SALES

/*A-3*/ --total pizzas sold
SELECT SUM(QUANTITY)AS TOTAL_PIZZAS_SOLD FROM PIZZA_SALES

/*A-4*/ --Total orders
SELECT COUNT(DISTINCT ORDER_ID)AS TOTAL_ORDERS FROM PIZZA_SALES

/*A-5*/ --Avg pizzas per order
SELECT CAST(CAST(SUM(QUANTITY)AS DECIMAL) /CAST(COUNT(DISTINCT ORDER_ID)AS DECIMAL(10,2))AS DECIMAL(10,2)) AS AVG_PIZZAS_PER_ORDER FROM PIZZA_SALES



/*DASHBOARD REQUIREMENT*/

--1 DAILY WISE TREND OF ORDERS
SELECT DATENAME(WEEKDAY,ORDER_DATE)AS ORDER_DAY, DATEPART(WEEKDAY,ORDER_DATE)AS DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY DATENAME(WEEKDAY,ORDER_DATE),DATEPART(WEEKDAY,ORDER_DATE)
ORDER BY 2 ASC

--2 MONTH WISE TREND OF ORDERS

SELECT DATENAME(MONTH, ORDER_DATE)AS ORDER_DAY, DATEPART(MONTH,ORDER_DATE)AS MONTH_NO, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY DATENAME(MONTH,ORDER_DATE),DATEPART(MONTH,ORDER_DATE)
ORDER BY 2 ASC

--3 PERCENTAGE OF SALES BY PIZZA CATEGORY

SELECT DISTINCT PIZZA_CATEGORY, SUM(TOTAL_PRICE) AS TOTAL_SALES, 
(SUM(TOTAL_PRICE)/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES )*100)AS PERCENT_OF_TOTAL FROM PIZZA_SALES

GROUP BY PIZZA_CATEGORY

--4 PERCENTAGE OF SALES BY PIZZA SIZE

SELECT DISTINCT PIZZA_SIZE, CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_SALES, 
CAST ((SUM(TOTAL_PRICE)/(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES )*100)AS DECIMAL(10,2)) AS PERCENT_OF_TOTAL FROM PIZZA_SALES

GROUP BY PIZZA_SIZE

--5 TOTAL PIZZAS BY PIZZA CATEGORY

SELECT PIZZA_CATEGORY, SUM(QUANTITY)AS TOTAL_PIZZAS FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY

--6 TOP 5 BEST SELLERS BY REVENUE, QUANTITY AND ORDERS

--BY REVENUE
SELECT TOP 5 PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REV FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY 2 DESC

--BY QUANTITY
SELECT TOP 5 PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QTY FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY 2 DESC

--BY ORDERS
SELECT TOP 5 PIZZA_NAME, COUNT(ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY 2 DESC


--7 BOTTOM 5 WORST SELLERS BY REVENUE, QUANTITY AND ORDERS

--BY REVENUE
SELECT TOP 5 PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REV FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY 2 ASC

--BY QUANTITY
SELECT TOP 5 PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QTY FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY 2 ASC

--BY ORDERS
SELECT TOP 5 PIZZA_NAME, COUNT(ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY 2 ASC


